---
- name: Install MySQL Yum Repo
  yum:
    name: https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm
    state: present
- name: Ensure MySQL packages are installed
  yum:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: rh_mysql_install_packages
- name: Push the template file
  template:
    src: serverdetails.j2
    dest: /tmp/serverdetails.txt
    mode: 0644