---
- name: Install MySQL Yum Repo
  yum:
    name: https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm
    state: present
- name: Ensure MySQL packages are installed
  yum:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: rh_mysql_install_packages
- name: Copy local file to Temp
  copy:
    src: ./roles/mysql/files/serverdetails.txt
    dest: /tmp/serverdetails.txt
- name: Check if file exists
  stat:
    path: /tmp/serverdetails.txt
  register: stat-file-serverdetails
- name: Change the permissions of the file
  become: true
  file:
    path: /tmp/serverdetails.txt
    mode: 0777
  when: stat-file-serverdetails.stat.exists

